require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
Style/SafeNavigationChainLength:
  Enabled: false
