# frozen_string_literal: true

require 'wikibase_representable/model/alias_group_list'
require 'wikibase_representable/model/alias_group'
require 'wikibase_representable/model/data_value'
require 'wikibase_representable/model/entity_id_value'
require 'wikibase_representable/model/entity_id'
require 'wikibase_representable/model/item'
require 'wikibase_representable/model/property_value_snak'
require 'wikibase_representable/model/property'
require 'wikibase_representable/model/site_link_list'
require 'wikibase_representable/model/site_link'
require 'wikibase_representable/model/snak_list'
require 'wikibase_representable/model/statement_list'
require 'wikibase_representable/model/statement'
require 'wikibase_representable/model/term_list'
require 'wikibase_representable/model/term'
require 'wikibase_representable/model/time_value'
require 'wikibase_representable/model/time'
