# frozen_string_literal: true

require 'wikibase_representable/model/snak_data_value_helper'
require 'wikibase_representable/model/statement_data_value_helper'

require 'wikibase_representable/model/alias_group_hash'
require 'wikibase_representable/model/data_value'
require 'wikibase_representable/model/entity_id'
require 'wikibase_representable/model/entity_id_value'
require 'wikibase_representable/model/item'
require 'wikibase_representable/model/property'
require 'wikibase_representable/model/property_value_snak'
require 'wikibase_representable/model/site_link'
require 'wikibase_representable/model/site_link_hash'
require 'wikibase_representable/model/snak_hash'
require 'wikibase_representable/model/statement'
require 'wikibase_representable/model/statement_hash'
require 'wikibase_representable/model/term'
require 'wikibase_representable/model/term_hash'
require 'wikibase_representable/model/time_value'
require 'wikibase_representable/model/time'
